version: 0.2

phases:
  install:
    commands:
      - echo "Starting Linting with tflint"
      - curl -sL https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
  pre_build:
    commands:
      - echo "Checking branch name..."
      - export BRANCH_NAME=$(echo $CODEBUILD_WEBHOOK_HEAD_REF | cut -d/ -f3)
      - echo "Running on branch - $BRANCH_NAME"
      - |
        if [[ "$BRANCH_NAME" != "fix/*" || "$BRANCH_NAME" != "feature/*" ]]; then
          echo "Skipping linting for branch $BRANCH_NAME"
          exit 0
        fi
  build:
    commands:
      - tflint -c .tflint.hcl

artifacts:
  files:
    - '**/*'
